#!/bin/bash
SELF=$(readlink -f "$0")
HERE=${SELF%/*}
export PATH="${HERE}/usr/bin/:${HERE}/usr/python/bin/:${HERE}/usr/sbin/:${PATH}"
export LD_LIBRARY_PATH="${HERE}/usr/lib/:${HERE}/usr/lib/x86_64-linux-gnu/:${HERE}/usr/lib32/:${HERE}/usr/lib64/:${HERE}/lib/:${HERE}/lib/x86_64-linux-gnu/:${HERE}/lib32/:${HERE}/lib64/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export XDG_DATA_DIRS="${HERE}/usr/share/:${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
export PYTHONPATH="${HERE}/usr/python/lib/python3.8/:${HERE}/usr/python/lib/python3.8/site-packages/:${PYTHONPATH:+:$PYTHONPATH}"
export PYTHONHOME="${HERE}/usr/python/"
cd "${HERE}/usr/bin"
exec "${HERE}/usr/bin/email-printer" "$@" 